# Generated by Django 2.2.2 on 2020-03-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre')),
                ('prom_factor', models.CharField(max_length=254, verbose_name='Factor promedio')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre')),
                ('prom_factor', models.CharField(max_length=254, verbose_name='Factor promedio')),
            ],
            options={
                'ordering': ('prom_factor',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected', models.CharField(max_length=254, verbose_name='Infectados')),
                ('recovered', models.CharField(max_length=254, verbose_name='Recuperados')),
                ('dead', models.CharField(max_length=254, verbose_name='Muertos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('chile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chile_page', to='core.Chile')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_page', to='core.World')),
            ],
        ),
    ]
