# Generated by Django 2.2.2 on 2020-03-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200325_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='world',
        ),
        migrations.AddField(
            model_name='world',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_world', to='core.Page'),
        ),
    ]
