# Generated by Django 2.2.2 on 2020-03-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200325_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre')),
                ('infected', models.CharField(max_length=254, verbose_name='Cant. Infectados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='chile',
        ),
        migrations.RemoveField(
            model_name='world',
            name='page',
        ),
    ]
