# Generated by Django 2.2.2 on 2020-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200325_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ('-infected',)},
        ),
    ]
