# Generated by Django 2.2.2 on 2020-03-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200326_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={},
        ),
    ]
