# Generated by Django 2.2.2 on 2020-03-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chiledatos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChileDatos',
            new_name='ChileData',
        ),
    ]
