# Generated by Django 2.2.2 on 2020-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200329_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiledata',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='chiledata',
            name='name',
            field=models.IntegerField(verbose_name='Datos de Chile'),
        ),
    ]
