# Generated by Django 2.2.2 on 2020-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200329_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='infected',
            field=models.IntegerField(verbose_name='Cant. Infectados'),
        ),
    ]
