# Generated by Django 2.2.2 on 2020-04-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newcases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCases',
        ),
    ]
